/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Console: typeof import('./src/components/Console.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingContent: typeof import('./src/components/SettingContent.vue')['default']
    ShortCut: typeof import('./src/components/ShortCut.vue')['default']
    ThemeSetting: typeof import('./src/components/ThemeSetting.vue')['default']
  }
}
