/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputTag: typeof import('@arco-design/web-vue')['InputTag']
    ALink: typeof import('@arco-design/web-vue')['Link']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Console: typeof import('./src/components/Console.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptPanel: typeof import('./src/components/ScriptPanel.vue')['default']
    SelectList: typeof import('./src/components/SelectList.vue')['default']
    SettingContent: typeof import('./src/components/SettingContent.vue')['default']
    ShortCut: typeof import('./src/components/ShortCut.vue')['default']
    ThemeSetting: typeof import('./src/components/ThemeSetting.vue')['default']
  }
}
