/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    ADropdownButton: typeof import('@arco-design/web-vue')['DropdownButton']
    ADropdownOption: typeof import('@arco-design/web-vue')['DropdownOption']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    ALink: typeof import('@arco-design/web-vue')['Link']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Console: typeof import('./src/components/Console.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Feature: typeof import('./src/components/Feature.vue')['default']
    FeatureContent: typeof import('./src/components/FeatureContent.vue')['default']
    FeatureForm: typeof import('./src/components/FeatureForm.vue')['default']
    FeatureItem: typeof import('./src/components/FeatureItem.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingContent: typeof import('./src/components/SettingContent.vue')['default']
    ShortCut: typeof import('./src/components/ShortCut.vue')['default']
    ThemeSetting: typeof import('./src/components/ThemeSetting.vue')['default']
  }
}
